postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: mighty-highfive
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - mighty-highfive-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - mighty-highfive-redis:/var/lib/redis/data

mighty-highfive:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/mighty-highfive
  ports:
    - '8000:8000'
  env_file:
    - .mighty-highfive.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/mighty-highfive
  env_file:
    - .mighty-highfive.env